# workflows/lint-markdown.yml
#
# Lint Markdown
# Lint Markdown files using markdownlint and Prettier.

name: Lint Markdown

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "**/*.md"
      - "**/*.mdx"
      - ".github/workflows/lint-markdown.yml"
  workflow_dispatch:

concurrency:
  group: lint-markdown-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-markdown:
    name: Lint Markdown Files
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v6

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up NodeJS Environment
        uses: actions/setup-node@v6
        with:
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Install markdownlint
        run: npm install -g markdownlint-cli

      - name: Run Markdown Lint
        run: markdownlint "**/*.md"

      - name: Run Prettier
        run: pnpm exec prettier --check "{**/*.md,**/*.mdx}" --ignore-path .prettierignore
