# workflows/lint-yaml.yml
#
# Lint YAML
# Lint YAML files using Prettier.

name: Lint YAML

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "**/*.yml"
      - "**/*.yaml"
      - ".github/workflows/lint-yaml.yml"
  workflow_dispatch:

concurrency:
  group: lint-yaml-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-yaml:
    name: Lint YAML Files
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v7

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up NodeJS Environment
        uses: actions/setup-node@v6
        with:
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts

      - name: Check YAML Formatting
        run: pnpm exec prettier --check "**/*.{yml,yaml}" --ignore-path .prettierignore
